# Generated by Django 5.0.1 on 2024-02-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('trans_floor', models.IntegerField()),
                ('com_year', models.IntegerField()),
                ('interest', models.FloatField()),
                ('household', models.IntegerField()),
                ('top_floor', models.IntegerField()),
                ('subway_dist', models.FloatField()),
                ('subway_cnt', models.IntegerField()),
                ('bus_cnt', models.IntegerField()),
                ('parking_lot', models.FloatField()),
                ('school', models.IntegerField()),
                ('hospital', models.IntegerField()),
            ],
        ),
    ]
