# Generated by Django 5.0.1 on 2024-02-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputData',
            new_name='InputDataModel',
        ),
    ]
